---
format_version: 2
environments:
  pocenv:
    environment_variables:
      DEPLOYMENT: testing
pipelines:
  proof_of_concept:
    group: mygroup
    lock_behavior: none
    parameters:
      param1: value1
    materials:
      powerbash:
        git: https://github.com/napalm255/powerbash.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            virtualenv:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Hello World"
