---
format_version: 2
environments:
  pocenv:
    environment_variables:
      DEPLOYMENT: testing
pipelines:
  setup:
    group: poc
    lock_behavior: none
    materials:
      powerbash:
        git: https://github.com/napalm255/powerbash.git
        branch: master
        destination: powerbash
      vmware_drs:
        git: https://github.com/napalm255/ansible-vmware_drs.git
        branch: master
        destination: vmware_drs
    stages:
      - setup:
          clean_workspace: true
          jobs:
            virtualenv:
              tasks:
                - exec:
                    command: /usr/bin/python
                    arguments:
                      - -m
                      - virtualenv
                      - venv
                - exec:
                    command: ../venv/bin/python
                    working_directory: vmware_drs
                    arguments:
                      - -m
                      - pip
                      - install
                      - -r
                      - requirements.txt
