---
format_version: 2
environments:
  poc:
    environment_variables:
      DEPLOYMENT: testing
    pipelines:
      - poc_setup
      - poc_build
      - poc_tests
      - poc_deploy
    agents:
      - 59694d0c-c8b8-4247-89d5-962f2f0bd0b4
pipelines:
  poc_setup:
    group: poc
    lock_behavior: none
    materials:
      vmware_drs:
        git: https://github.com/napalm255/ansible-vmware_drs.git
        branch: master
        destination: vmware_drs
    artifacts:
      - venv:
          source: venv/
          destination: venv/
    stages:
      - setup:
          jobs:
            virtualenv:
              resources:
                - python
              tasks:
                - exec:
                    command: /usr/bin/python
                    arguments:
                      - -m
                      - virtualenv
                      - venv
                - exec:
                    command: ../venv/bin/python
                    working_directory: vmware_drs
                    arguments:
                      - -m
                      - pip
                      - install
                      - -r
                      - requirements.txt
  poc_build:
    group: poc
    lock_behavior: none
    materials:
      powerbash:
        git: https://github.com/napalm255/powerbash.git
        branch: master
        destination: powerbash
    tabs:
      build: powerbash.sh
    artifacts:
      - results:
          source: powerbash.sh
          destination: powerbash.sh
    stages:
      - build:
          jobs:
            build:
              resources:
                - linux
              tasks:
                - exec:
                    command: /bin/cat
                    arguments:
                      - powerbash.sh
  poc_tests:
    group: poc
    lock_behavior: none
    materials:
      build:
        pipeline: poc_build
        stage: build
    tabs:
      test: unit_tests.txt
    stages:
      - tests:
          jobs:
            unit_tests:
              resources:
                - linux
              tasks:
                - fetch:
                    pipeline: poc_build
                    stage: build
                    job: build
                    source: powerbash.sh
                    destination: powerbash.sh
                - exec:
                    command: /bin/cat
                    arguments:
                      - powerbash.sh
            sonar:
              resources:
                - linux
              tasks:
                - fetch:
                    pipeline: poc_build
                    stage: build
                    job: build
                    source: powerbash.sh
                    destination: powerbash.sh
                - exec:
                    command: /bin/cat
                    arguments:
                      - powerbash.sh
            owasp:
              resources:
                - linux
              tasks:
                - fetch:
                    pipeline: poc_build
                    stage: build
                    job: build
                    source: powerbash.sh
                    destination: powerbash.sh
                - exec:
                    command: /bin/cat
                    arguments:
                      - powerbash.sh
  poc_deploy:
    group: poc
    lock_behavior: none
    materials:
      setup:
        pipeline: poc_setup
        stage: setup
      build:
        pipeline: poc_build
        stage: build
      tests:
        pipeline: poc_tests
        stage: tests
    tabs:
      build: deploy_artifact.txt
    stages:
      - deploy:
          jobs:
            deploy:
              resources:
                - linux
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "echo Hello World!"
                      - ">"
                      - deploy_artifact.txt
