---
format_version: 2
environments:
  poc:
    environment_variables:
      DEPLOYMENT: testing
    pipelines:
      - poc_setup
      - poc_build
    agents:
      - 59694d0c-c8b8-4247-89d5-962f2f0bd0b4
pipelines:
  poc_setup:
    group: poc
    lock_behavior: none
    materials:
      vmware_drs:
        git: https://github.com/napalm255/ansible-vmware_drs.git
        branch: master
        destination: vmware_drs
    stages:
      - setup:
          clean_workspace: true
          jobs:
            virtualenv:
              resources:
                - python
              tasks:
                - exec:
                    command: /usr/bin/python
                    arguments:
                      - -m
                      - virtualenv
                      - venv
                - exec:
                    command: ../venv/bin/python
                    working_directory: vmware_drs
                    arguments:
                      - -m
                      - pip
                      - install
                      - -r
                      - requirements.txt
  poc_build:
    group: poc
    lock_behavior: none
    materials:
      powerbash:
        git: https://github.com/napalm255/powerbash.git
        branch: master
        destination: powerbash
    tabs:
      build: build_artifact.txt
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
                - linux
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "echo Hello World!"
                      - ">"
                      - build_artifact.txt
  poc_tests:
    group: poc
    lock_behavior: none
    materials:
      build:
        pipeline: poc_build
        stage: build
    tabs:
      test: unit_tests.txt
    stages:
      - tests:
          clean_workspace: true
          jobs:
            unit_tests:
              resources:
                - linux
              tasks:
                - fetch:
                    pipeline: poc_build
                    stage: build
                    job: build
                    source: build_artifact.txt
                    destination: build_artifact.txt
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "echo UNIT TESTS!"
                      - ">"
                      - unit_tests.txt
            sonar:
              resources:
                - linux
              tasks:
                - fetch:
                    pipeline: poc_build
                    stage: build
                    job: build
                    source: build_artifact.txt
                    destination: build_artifact.txt
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "echo SONAR!"
                      - ">"
                      - sonarqube.txt
            owasp:
              resources:
                - linux
              tasks:
                - fetch:
                    pipeline: poc_build
                    stage: build
                    job: build
                    source: build_artifact.txt
                    destination: build_artifact.txt
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "echo OWASP!"
                      - ">"
                      - owasp.txt
  poc_deploy:
    group: poc
    lock_behavior: none
    materials:
      setup:
        pipeline: poc_setup
        stage: setup
      build:
        pipeline: poc_build
        stage: build
    tabs:
      build: deploy_artifact.txt
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - linux
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "echo Hello World!"
                      - ">"
                      - deploy_artifact.txt
